cement/config/routes.rb
Cement::Application.routes.draw do

  root :to => 'users#welcome'

  resources :items do
      post 'remove', :on => :member
      get  'rep_txnitems', :on => :member
      get  'all_search', :on => :collection
      get  'aggrigated_summary', :on => :collection

  end

  resources :contacts do
    post 'remove', :on => :member
    post  'reports', :on => :member
    post  'ajax_create', :on => :collection

    get 'search_names', :on => :collection
    get  'add_txn', :on => :collection
    get  'window_list', :on => :collection
    get  'report_page', :on => :member
    get 'excel_export', :on => :member

    get 'quick_edit' , :on => :collection
    get 'all_edit' , :on => :collection

    post 'quick_update' , :on => :collection
    post 'all_edit' , :on => :collection
    post 'save_filter', :on => :collection
    post 'filter', :on => :collection
    get  'show_filter', :on => :collection 
    
  end

  resources :transactions do
    post 'remove', :on => :member
    get  'add_item_row', :on => :collection
    post 'pagination', :on => :collection
    get  'quick_add_form', :on => :collection
    post 'quick_add', :on => :collection
  end

  resources :stock_entries do
    post 'remove', :on => :member
    get  'add_item_row', :on => :collection
    post 'pagination', :on => :collection
    get  'quick_add_form', :on => :collection
    post 'quick_add', :on => :collection
    get  'contact_stock', :on => :member
  end

  resources :sites do
    get  'window_list', :on => :collection
    get 'search_names', :on => :collection
    post 'remove', :on => :member
    get 'rep_txnitems', :on => :member
    get 'contact_txnitems', :on => :member
  end

  resources :transaction_types do
      post 'remove', :on => :member

    resources :custom_fields do
      get 'remove', :on => :member
    end  

  end  

  resources :users do
    post 'enter_in', :on => :collection
    get 'ask_signin', :on => :collection
    get 'change_password', :on => :member
    get 'activate', :on => :member
    get 'inactivate', :on => :member
    post 'remove', :on => :member
    put 'save_new_password', :on => :member
    get 'reset_password', :on => :member
    get 'logout', :on => :member
    get  'no_access', :on => :collection
    get  'self_details', :on => :member
  end  

  resources :payments do
      post 'remove', :on => :member
      get  'add_payment_row', :on => :collection
  end   

   resources :reports do
      post 'generate', :on => :collection
      get 'saved_message', :on => :member
      
   end 

   resources :analytics do
      get  'sort_baldtls', :on => :collection
      get  'sales', :on => :collection
      get  'sort_itemsales', :on => :collection
      post 'filter_block1', :on => :collection
      post 'filter_block2', :on => :collection
      post 'filter_block3', :on => :collection
      put  'filter_block1', :on => :collection
   end 

   get "status", to:"analytics#aggr_payments"

end
    
    

cement/app/models/transaction_type.rb
class TransactionType < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :custom_fields,  :dependent => :destroy
  has_many :field_values
  has_one :creater, :class_name => "User", :foreign_key => 'created_by'
  has_one :modifier, :class_name => "User", :foreign_key => 'modified_by'

  
end

cement/app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  @@available_action = ['new_sale','new_return','new_payment']
 
 def index
  @sort_column = params[:sort_colum] || 'on_date'
  @sort_order = params[:sort_order]  || "DESC"
  @page_size = params[:page_size] || 20

  no_of_weeks =  params[:no_of_weeks].blank? ? 2 : params[:no_of_weeks].to_i
  date_str = "on_date > '"+no_of_weeks.weeks.ago.strftime("%Y-%m-%d")+"' " if no_of_weeks > 1
  @trs_text = "Showing  transactions from last "+no_of_weeks.to_s+" weeks ."
  
  if !params[:from_date].blank? || !params[:to_date].blank?
    from_date = ( params[:from_date].blank? ?  '2000-01-01': DateTime.parse(params[:from_date]).strftime('%Y-%m-%d %H:%M'))
    to_date   = ( params[:to_date].blank? ? '2100-01-01' : DateTime.parse(params[:to_date]).strftime('%Y-%m-%d %H:%M') )
    date_str  = " on_date  between '"+from_date+"' and '"+to_date+"'"
    @trs_text = " Showing transactions "
    @trs_text += " from "+params[:from_date] if  !params[:from_date].blank?
    @trs_text += " up to "+params[:to_date] if  !params[:to_date].blank?
  end
  offset = params[:offset] || 0
  total = Transaction.count
  @trs = Transaction.where(date_str).order("#{@sort_column} #{@sort_order}, created_at DESC ")
  
 end

 def show
 end

 def new
   @trans = Transaction.new
   @form_method = 'post'
   render :action => params[:tx_type] if  @@available_action.include?(params[:tx_type])
 end

 def new_sale
 end
 
 def new_return
 end 

 def new_payment
 end 

 def edit
   @trans = Transaction.find(params[:id])
   @contact_name = @trans.contact.name.to_s+" "+@trans.contact.subname.to_s
   @site_name = (@trans.site.blank? ?  "":@trans.site.name)
   @form_method = 'put '
 end

 def create
  p "PARAMS"
  p params
    @trans = Transaction.new(params[:transaction])
    @trans.created_by = @auser.id
    params[:txn_items].each{ |key,val|
     item_params = val
     unless ( item_params[:item_id].blank? || item_params[:item_id].to_i == 0) && item_params[:item_descri].blank? 
      ti = TxnItem.new(item_params)
      ti.contact_id = params[:transaction][:contact_id]
      ti.amount = ti.calculate_amount
      ti.buyback_now = @trans.buyback
      @trans.txn_items << ti
     end 
    }

     contact_name = params[:txn][:contact].strip
      if !contact_name.blank? and  contact_name.length > 3
        cnt =  Contact.find(params[:transaction][:contact_id]) if !params[:transaction][:contact_id].blank?
        if cnt.blank? || cnt.name_subname != contact_name
            contact = Contact.new
            contact.name = contact_name
            contact.regular = 0
            contact.save!
            @trans.contact_id = contact.id
        end  
         
      end  

     site_param = params[:txn][:site].strip
     if !site_param.blank? and  site_param.length > 3
       site = Site.find_by_name(site_param)
       if site == nil
         site = Site.new
         site.name = site_param
         site.save!
       end 
      


       @trans.site = site
     end
   begin
      @trans.save!
      @trs = Transaction.all
      rl = 
      flash[:notice] = 'Transaction# '+@trans.id.to_s+' added Successfully !'
      flash.keep(:notice)

      if params[:commit] == 'Save and +New'
     
            #format.js {render 'save_and_ad_new', layout: false}
              url = quick_add_form_transactions_path
              render js: "window.location.pathname='#{url}'"
      else
        url = report_page_contact_path(:id => @trans.contact_id)
        render js: "window.location.pathname='#{url}'"
      end  
      #render js: "window.location.pathname='#{transactions_path}'"

      
    rescue Exception => e
     p e.to_s
     @serr = e.to_s
     respond_to do |format|
       format.js {render layout: false}

     end  
   end
    

    
    #redirect_to :action => 'index'

  end

 def update
   @trans = Transaction.find(params[:id])
   txn_ids = []
   params[:txn_items].each{|key,val|

      id = key.to_i
      txn_ids << id
      
     
      if id.to_i < 1000 
        ti = TxnItem.new(val)
        ti.created_by = @auser.id
        ti.calculate_amount
        ti.save!
        @trans.txn_items <<   ti
        txn_ids << ti.id
      else
         old_txi = TxnItem.find(id)  
         
         if old_txi.item_id != val[:item_id].to_i || old_txi.price != val[:price].to_f || old_txi.number != val[:number].to_i
           val[:updated_by] = @auser.id
           val[:amount] = val[:price].to_f * val[:number].to_i
           val[:buyback_was] = @trans.buyback
           val[:buyback_now] = params[:transaction][:byback].to_i
           old_txi.update_attributes(val)          
         end          
      end 
    
    } unless  params[:txn_items].blank?

      @trans.txn_items.each{|txn|
        txn.destroy if  !txn_ids.include?(txn.id)
      }

     site_param = params[:txn][:site]

     if !site_param.blank? and  site_param.length > 3
       site = Site.find_by_name(site_param)
   
       if site == nil
         site = Site.new
         site.name = site_param
         site.save!
       end 
       params[:transaction][:site_id] = site.id

     end

    begin  
     p "CALLING 1"
     @trans.skip_updator = true
     @trans.save!
     #@trans(params[:transaction])
     p "CALLING 2"
     @trans.skip_updator = false
     @trans.update_attributes(params[:transaction])


     render js: "window.location.pathname='#{transactions_path}'"
    rescue Exception => e
     p e.to_s
     @serr = e.to_s
       respond_to do |format|
         format.js {render layout: false}

       end  
    end
  
 end

 def destroy
 end

def remove
  begin
    txn = Transaction.find(params[:id])
    cid = txn.contact_id
    txn.destroy
   flash[:notice] = 'Transaction# '+params[:id]+' deleted Successfully !'
   flash.keep(:notice)
   if(params[:show_page] == 'report_page')
     redirect_to  report_page_contact_path(:id => cid)
   else
    redirect_to :action => 'index'
   end 
   
  
  rescue Exception => e 
    p e.to_s
    p e.backtrace
  end  
 end

 def add_item_row
   row_no = params[:no]
   @row_no = row_no.to_i + 1
   @txn_item = TxnItem.new 
   respond_to do |format|
     format.js {render layout: false}
   end
 end 

 def search_contact
   contacts = Contact.trns_search(params[:str])
   respond_to do |format|
      format.json {render layout: false}
   end   

 end 

 def pagination
   
  @sort_column = params[:sort_colum] || 'on_date'
  @sort_order = params[:sort_order]  || "DESC"
  @page_size = params[:page_size] || 20

  no_of_weeks =  params[:no_of_weeks].blank? ? 2 : params[:no_of_weeks].to_i
  date_str = "on_date > '"+no_of_weeks.weeks.ago.strftime("%Y-%m-%d")+"' " if no_of_weeks > 1
  @trs_text = "Showing  transactions from last "+no_of_weeks.to_s+" weeks ."
  
  date_str = "on_date >  '"+1.months.ago.strftime("%Y-%m-%d")+"'" if params[:month_ago] == 'true'

  if !params[:from_date].blank? || !params[:to_date].blank?
    from_date = ( params[:from_date].blank? ?  '2000-01-01': DateTime.parse(params[:from_date]).strftime('%Y-%m-%d %H:%M'))
    to_date   = ( params[:to_date].blank? ? '2100-01-01' : DateTime.parse(params[:to_date]).strftime('%Y-%m-%d %H:%M') )
    date_str  = "on_date  between '"+from_date+"' and '"+to_date+"'"
    @trs_text = "Showing transactions "
    @trs_text += " from "+params[:from_date] if  !params[:from_date].blank?
    @trs_text += " up to "+params[:to_date] if  !params[:to_date].blank?
  end

   @trs = Transaction.where(date_str).order("#{@sort_column} #{@sort_order}, created_at DESC ")

   respond_to do |format|
      format.js {render layout: false}
   end 
 end 

 def quick_add_form

  @trans = Transaction.new
  @cont = Contact.all_conts
  @sites = Site.all
   
 end 

 def quick_add
 end


 
end

cement/app/helpers/transaction_helper.rb
module TransactionHelper

	def array_text_field(object_name,field_name,style_str,value,row_number = nil)
	   str =	"<input type='text' class = 'input item_numbers' name='"+object_name+"["+row_number+"]["+field_name+"]' id='"+object_name+"_"+field_name+"_"+row_number+"'"
	   str += " size='10' style='"+style_str+"'" unless style_str.blank?
	   str += " value='"+ value+"' /> "
      return str.html_safe

	end	


	def array_select(object_name,field_name,style_str,option_values,row_number = nil)
		str =  	"<select  class = 'input item_val' name='"+object_name+"["+row_number.to_s+"]["+field_name+"]' id='"+object_name+"_"+field_name+"_"+row_number+"'"
	    str += " style='"+style_str+"'" unless style_str.nil?
	    str += ">"
	    str += " <option value =''></value>"
        str += option_values
        str += '</select>'

        return str.html_safe
	end	
end

cement/app/views/transactions/_form.erb
  
<div id='contact-modal-window' class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" scrollable ="true">
 Loading ...
</div>

<%= form_for @trans,  :method => @form_method, :remote => true, :html =>{:id=>'transaction_form'} do |f| %>

   
  <div  id='form_elements' class="row-fluid txn-form" style="padding-bottom : 0px;">
     <div class="span1" >

     </div>
     <div class="span3" >
        Date : <br><%= f.text_field :on_date, class:'input', style:'height:30px;width:150px'%>
     </div>
     <div class="span3">
        Customer: <%= link_to '+New', add_txn_contacts_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#contact-modal-window', style: 'font-size:12px;font-weight:bold;'}  %> &nbsp;|
        <%=link_to ((image_tag "find.png", :size=>"16x16")+" List"), window_list_contacts_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#contact-modal-window', style: 'font-size:12px;font-weight:bold;'}  %> 
          <br>
       
        <%=text_field :txn, :contact, class:'autocomplete', style:"height:30px;"%>
        <%=f.hidden_field :contact_id %>
        <br>
        <span id='contact_number' style='color:grey;font-size:14px;'></span>
 <br>
     </div>
     &nbsp;&nbsp;
     <div class="span3">
        Site:  <%=link_to ((image_tag "find.png", :size=>"16x16")+" List"), window_list_sites_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#contact-modal-window', style: 'font-size:12px;font-weight:bold;'}  %> <br> 
        <%=text_field  :txn, :site, class:'autocomplete', style:"height:30px;"%> <br>
        <%=f.hidden_field :site_id %>
     </div>
     

  </div>
   <% @row_no ||= 1 %>
<div id='div_item_table' class="row-fluid txn-form">
 <div class="span1" >
     </div>
 <div class="span10">
    <table id='item_tb' class='table' border='0' >
      <thead style="font-size:12px;">
         <th id='item_th' style="padding:2px;"><%=link_to '+ Item', add_item_row_transactions_path(:id => '0',:no => @row_no ), :remote => true%></th>
         <th style="padding:2px;">Description</th>
         
         <th style="padding:2px;">Quantity</th>
         <th style="padding:2px;">Rate</th>
         <th style="padding:4px;">Amount</th>
         <th></th>
      </thead> 
      <tbody style='font-size:13px;'>
      
          <%=render partial:'item_row.erb', locals: {row_no: 1}%>
          <tr id='gap_row' class='borderless'>
            <td ></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
        
        <tr>
          <td style='border-top:0px;padding:2px;'> Vehicle Rental: <br> 
             <%=f.text_field :vehicle_charges, style:'height:30px;', :class=>'calc-amount'%>
          </td>
          <td style='border-top:0px;padding:2px;padding-left:8px;'> Hamaali: <br> 
             <%=f.text_field :hamaali, style:'height:30px;', :class=>'calc-amount'%>
          </td>
          <td style='border-top:0px;padding:2px;'>Discount:
           <br> 
             <%=f.text_field :discount, style:'height:30px;width:100px;', :class=>'calc-amount'%>

          </td>
          <td style="border-top:0px;font-size:13px;"><br><b>Total Amount</b></td>
         <td style="border-top:0px;"> <div id='items_total_value' style='padding-top:20px;'>0</div></td>
        </tr>
      </tbody>  

  </table>
  <hr>
  </div>
</div> 

<div class="row-fluid txn-form">
   <div class="span1" >
     </div>
   <div class="span3" >
      Payment Type
     <br>
     <%=f.select  :payment_type, [['Cash','Cash'],['Cheque','Cheque'],['Bank Transaction']],{},{style:'width:150px;'}%>
     
   </div>
   <div class="span3">
        Payment Note
      <br>
      <%=f.text_field :payment_note, style:'height:30px;'%>
   </div>

   <div class="span2">
     Paid Amount 
     <br>
     <%=f.text_field  :payment_amount, style:'height:30px;'%>
   </div>

</div>  

<div class="row-fluid txn-form">
   <div class="span1" >
     </div>
   <div class="span4" style="padding:0px;" >

      Note:<br><%=text_area  :transaction, :descri , :size=>'2X10' %>
   </div>

   <div  class="span3" style="padding-left:1px;padding-top:40px;" >

      <span class="label label-info"> Return: <%=check_box  :transaction, :buyback %> </span>
   </div>
      
  </div>

<div class="row-fluid txn-form">
  <div class="span1" >
     </div>
  <div class="span11">
     <hr>
     <%=submit_tag 'Save Transaction',  class:'btn btn-warning', :data => {disable_with: "Saving ..."}, id:'tx-btn'%><%=space(5).html_safe%>
     <%=submit_tag 'Save and +New',  class:'btn btn-success', :data => {disable_with: "Saving ..."}, id:'tx-btn'%><%=space(5).html_safe%>
      <%=link_to "Cancel", transactions_url, :style=>"font-weight:bold"%>

  </div>
</div>

 
<% end %>



 
<script type="text/javascript">

$('#transaction_on_date').datepicker({ dateFormat: 'dd-mm-yy' });
$("#transaction_on_date").datepicker('setDate', new Date());
$('.calc-amount').on('keyup', function(){
    
     calc_total_value();

   });

  var contact_names = [];
  var search_contacts = {};
  var site_names = [];
  var search_sites = [];

  $('#txn_contact').autocomplete({
    minLength: 2,
    source: function (request,response){
               a =  $("#txn_contact")[0].value;
               $.ajax({
               type:"Get",
               dataType: 'json',
               url: "<%=search_names_contacts_path()%>",
               data:"str="+a ,
               success: function(data){
                contact_names = [];
                search_contacts = {};
                 $.each(data, function(i,val){
                     
                    n_name = (val.subname == null ? val.name:val.name+" "+val.subname)
                    contact_names.push(n_name);
                    search_contacts[n_name] = val;
                 });
                   
               }
             });
              response(contact_names);
           },
    select: function( event, ui ) { 
              
                $('#transaction_contact_id').val(search_contacts[ui.item.value].id.toString());
                 $('#contact_number').html("Ph: "+search_contacts[ui.item.value].contact_number)

              }       

  });


  $('#txn_site').autocomplete({
    minLength: 2,
    source: function (request,response){
               a =  $("#txn_site")[0].value;
               $.ajax({
               type:"Get",
               dataType: 'json',
               url: "<%=search_names_sites_path()%>",
               data:"str="+a ,
               success: function(data){
                site_names = [];
                search_sites = {};
                 $.each(data, function(i,val){
                    site_names.push(val.name);
                    search_sites[val.name] = val.id;
                 });
                   
               }
             });
              response(site_names);
           },
     select: function( event, ui ) { 
      $('#transaction_site_id').val(search_sites[ui.item.value].toString());}       

  });

  $('#txn-btn').click(function(){
    $(this).attr('disabled', true);
});
 
</script>

cement/app/views/transactions/add_item_row.js.erb
$('#others_row').before("<%= j(render  :template => 'transactions/_item_row_2.erb', :locals => {:row_no => @row_no} ) %>");
$('#item_th').html("<td style='border-top: 0px solid #DDDDDD;'> <%=j (link_to ((image_tag 'add.png', :size=>'10x10')+'Item'), add_item_row_transactions_path(:id => '0',:no => @row_no ), :remote => true)%></td>")

cement/app/views/transactions/edit.html.erb
<div id='contact-modal-window' class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
</div>

<%= form_for @trans, :remote => true, :html =>{:id=>'transaction_form'} do |f| %>
  
   <div id='Header' class="row-fluid txn-form">
     <div class="span10 offset2" >
     <h4>Edit Transaction <%=@trans.id%></h4>
     </div>
   </div> 

 <div id='div_item_table' class="row-fluid txn-form" style="border:0;">
    <div class="span2" ></div>
    <div class="span8">

        <table id='item_tb' class=' nb-table' style="border:1px solid #e6e6e6; background-color: #f1f1f1;">
      <thead style="font-size:12px;">
      </thead> 
      <tbody style='font-size:13px;'>
         <tr id='first_row_fields'>
             <td style="padding:20px;padding-bottom:10px;"> Date : <%=@trans.on_date%></td>
             <td  style="width:20%;padding-bottom:1px;">  <%=@trans.contact.name_subname%>
                <%=f.hidden_field :contact_id %>
                <br>
                <span id='contact_number' style='color:grey;font-size:14px;'><%=@trans.contact.contact_number%></span>
             </td>
             <td style="padding-left:80px;padding-top:10px;">Site:  <%=link_to ((image_tag "find.png", :size=>"16x16")+" List"), window_list_sites_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#contact-modal-window', style: 'font-size:12px;font-weight:bold;'}  %> <br>
               <%=text_field :txn, :site, class:'autocomplete', style:"height:30px;", :value => @site_name%> <br>
               <%=f.hidden_field :site_id %>
             </td>
          </tr>
             


       <% @row_no ||= -1 %>
         <tr>
           <td id='item_th' style="padding:4px;width:35%;">&nbsp;<%=link_to ((image_tag "add.png", :size=>"10x10")+' Item'), add_item_row_transactions_path(:no => @row_no ), :remote => true%></td>
          </tr> 
       
        
        <%@trans.txn_items.each  do |item| %>
           <%= fields_for "txn_items[]", item do |t| %>
            <tr id="trow_<%=item.id%>" class='item_area'>
                <td style="padding:4px;" class='item_arr_no'>
                 <%=link_to_function  (image_tag "cross_circle.png", :size=>"12x12"), "removeItem('#{item.id}')", style:'font-size:15px;font-weight:bold;'%>
                    <%=t.select  :item_id,  options_for_select(["Select ..",'']+Item.all.collect{|c| [c.name,c.id]},["#{item.item.name} ", item.item_id ]), {}, {id:"item_select_#{item.id}",class:'item-select'} %>

                </td>
                
               <td style="padding:1px;padding-top:8px;border:0;" class='item_arr_no' colspan='2'> 
                 <%=t.text_field :number, id:"item_number_#{item.id}", class:"item_numbers", :style=>"width:100px;height:30px;" %>
                   <%=space(4)%>
                   <%=t.text_field :price, id:"item_price_#{item.id}",  class:"item_numbers", :style=>"height:30px;width:100px;"%> 
              <%=space(23)%>
               <span id='item_val_<%=item.id%>' class='item_total'> <%= Utility.indian_number item.amount%></span></td>

             </tr>
         <%end%>
       <%end%>
        
        
        <tr id='others_row'>
          <td style='border-top:0px;padding:10px;padding-left:16px;'> Vehicle Rental: <br> 
             <%=f.text_field :vehicle_charges, style:'height:30px;', :class=>'calc-amount'%>
          </td>
          <td style='border-top:0px;padding:2px;' colspan="2">
             Hamaali: <%=space(20)%> Discount: <br>
             <%=f.text_field :hamaali, style:'height:30px;width:100px;', :class=>'calc-amount'%>
            
              <%=space(5)%>
             <%=f.text_field :discount, style:'height:30px;width:100px;', :class=>'calc-amount'%>

          </td>
          </tr>
          <tr>
             <td style="border-top:0px;"></td>
             <td style="border-top:0px;font-size:13px;text-align:right;"><br><b>Total Amount</b></td>
             <td style="padding-left:100px;"> <span id='items_total_value'  style='padding-top:20px;'><%= Utility.indian_number @trans.amount%></span></td>
         
        </tr>

    <tr>

    <tr id='gap_row_3' >
            <td style="padding:10px;border-bottom: 1px solid #E6E6E6;" colspan="3"></td>
           </tr> 
      <td style="padding:20px;">
      Payment Type
       <br>
     <%=f.select  :payment_type, options_for_select([['Cash','Cash'],['Cheque','Cheque'],['Bank Transaction']],[@trans.payment_type,@trans.payment_type] ),{},{style:'width:150px;'}%>
     
      </td>

     <td>
       Paid Amount 
        <br>
        <%=f.text_field  :payment_amount, style:'height:30px;'%>
   </td>
     <td style="padding-left:80px;">
       <span  class="label "> Return: <%=f.check_box :buyback %> </span>
     </td>
</tr>  

    <tr>
             <td id='t_note' style="padding-left:20px;" colspan="3">
                Note: <br> <span><%=f.text_area  :descri , :size=>'2X10' %></span>
             </td>
         
        </tr>


 <tr id='gap_row_3' >
            <td style="padding:10px;border-bottom: 1px solid #E6E6E6;" colspan="3"></td>
           </tr> 

<tr>
    <tr>
     <td style="padding:20px;padding-right:0px;" colspan="3">
        <%=submit_tag 'Update Transaction',  class:'btn btn-warning', :data => {disable_with: "Saving ..."}, id:'tx-btn'%><%=space(5).html_safe%> <%=link_to "Cancel", transactions_url, :style=>"font-weight:bold"%>
       </td>
       <td  colspan="2"><%=link_to "X Delete", remove_transaction_url(:id => @trans.id, :show_page => 'report_page'), :method => :post,  :confirm => "Transaction #{@trans.id} will be deleted permanently !!  Are you Sure ?", :class=>"label label-warning"%></td>
       <tr>
      </tbody>  

  </table>
<% end %>

<script type="text/javascript">

$('.item-select').select2({
    width:'210px',

 });

$('#transaction_on_date').datepicker({ dateFormat: 'dd-mm-yy' });

$('.calc-amount').on('keyup', function(){
    
     calc_total_value();

   });
  var contact_names = [];
  var search_contacts = {};
  var site_names = [];
  var search_sites = [];

  $('#txn_contact').autocomplete({
    minLength: 2,
    source: function (request,response){
               a =  $("#txn_contact")[0].value;
               $.ajax({
               type:"Get",
               dataType: 'json',
               url: "<%=search_names_contacts_path()%>",
               data:"str="+a ,
               success: function(data){
                contact_names = [];
                search_contacts = {};
                 $.each(data, function(i,val){
                    n_name = (val.subname == null ? val.name:val.name+" "+val.subname)
                    contact_names.push(n_name);
                    search_contacts[n_name] = val;
                 });
                   
               }
             });
              response(contact_names);
           },
    select: function( event, ui ) { 
              
                $('#transaction_contact_id').val(search_contacts[ui.item.value].id.toString());
                 $('#contact_number').html("Ph: "+search_contacts[ui.item.value].contact_number)

              }       

  });


  $('#txn_site').autocomplete({
    minLength: 2,
    source: function (request,response){
               a =  $("#txn_site")[0].value;
               $.ajax({
               type:"Get",
               dataType: 'json',
               url: "<%=search_names_sites_path()%>",
               data:"str="+a ,
               success: function(data){
                site_names = [];
                search_sites = {};
                 $.each(data, function(i,val){
                    site_names.push(val.name);
                    search_sites[val.name] = val.id;
                 });
                   
               }
             });
              response(site_names);
           },
     select: function( event, ui ) { 
      $('#transaction_site_id').val(search_sites[ui.item.value].toString());}       

  });


$('#txn-btn').click(function(){
    $(this).attr('disabled', true);
});
 
 
</script>

cement/app/views/transactions/update.js.erb
$('#form_elements').before("<%= j(render  :template => 'transactions/_trans_error.erb', :locals => {:trans => @trans} ) %>");
$('#txn-btn').removeAttr("disabled");