cement/config/routes.rb
Cement::Application.routes.draw do

  root :to => 'users#welcome'

  resources :items do
      post 'remove', :on => :member
      get  'rep_txnitems', :on => :member
      get  'all_search', :on => :collection
      get  'aggrigated_summary', :on => :collection

  end

  resources :contacts do
    post 'remove', :on => :member
    post  'reports', :on => :member
    post  'ajax_create', :on => :collection

    get 'search_names', :on => :collection
    get  'add_txn', :on => :collection
    get  'window_list', :on => :collection
    get  'report_page', :on => :member
    get 'excel_export', :on => :member

    get 'quick_edit' , :on => :collection
    get 'all_edit' , :on => :collection

    post 'quick_update' , :on => :collection
    post 'all_edit' , :on => :collection
    post 'save_filter', :on => :collection
    post 'filter', :on => :collection
    get  'show_filter', :on => :collection 
    
  end

  resources :transactions do
    post 'remove', :on => :member
    get  'add_item_row', :on => :collection
    post 'pagination', :on => :collection
    get  'quick_add_form', :on => :collection
    post 'quick_add', :on => :collection
  end

  resources :stock_entries do
    post 'remove', :on => :member
    get  'add_item_row', :on => :collection
    post 'pagination', :on => :collection
    get  'quick_add_form', :on => :collection
    post 'quick_add', :on => :collection
    get  'contact_stock', :on => :member
  end

  resources :sites do
    get  'window_list', :on => :collection
    get 'search_names', :on => :collection
    post 'remove', :on => :member
    get 'rep_txnitems', :on => :member
    get 'contact_txnitems', :on => :member
  end

  resources :transaction_types do
      post 'remove', :on => :member

    resources :custom_fields do
      get 'remove', :on => :member
    end  

  end  

  resources :users do
    post 'enter_in', :on => :collection
    get 'ask_signin', :on => :collection
    get 'change_password', :on => :member
    get 'activate', :on => :member
    get 'inactivate', :on => :member
    post 'remove', :on => :member
    put 'save_new_password', :on => :member
    get 'reset_password', :on => :member
    get 'logout', :on => :member
    get  'no_access', :on => :collection
    get  'self_details', :on => :member
  end  

  resources :payments do
      post 'remove', :on => :member
      get  'add_payment_row', :on => :collection
  end   

   resources :reports do
      post 'generate', :on => :collection
      get 'saved_message', :on => :member
      
   end 

   resources :analytics do
      get  'sort_baldtls', :on => :collection
      get  'sales', :on => :collection
      get  'sort_itemsales', :on => :collection
      post 'filter_block1', :on => :collection
      post 'filter_block2', :on => :collection
      post 'filter_block3', :on => :collection
      put  'filter_block1', :on => :collection
   end 

   get "status", to:"analytics#aggr_payments"

end
    
    

cement/app/models/bill.rb
class Bill < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :transaction
  has_many :items

end

cement/app/models/contact.rb
class Contact < ActiveRecord::Base
  
  include BaseUtils
  audited :allow_mass_assignment => true
  
 # attr_accessible :name_subname
  has_many :sites
  has_many :transactions
  has_many :payments
  
  #before_create :assign_balance
  #after_update  :rectify_contact_balance

 # before_update  :rectify_contact_balance

  validates :name, :presence => { :message => " Cannot be blank" }
  validates :name, uniqueness: { scope: :subname,
  message: "Contact already exists. Try with different name or tag name" }

  def unique_contact

    if Contact.exists?(:name => self.name, :subname => self.subname)
     errors.add(:base,"Contacts already exists, try with different name or tag name") 
    end
  end  

  def name_subname
    return subname.blank? ? name : name+ " "+subname
  end 

  def name_subname_underscore
     gname = name.gsub(' ','_')
     gsname = subname.to_s.gsub(' ','_')
     return subname.blank? ? gname : gname+ " "+gsname
  end 

  def parent
   Contact.find(self.parent_id) unless self.parent_id.blank?
  end

  def self.trns_search(str)
  	s_contacts = self.where("name  like '#{str}%' or subname  like '#{str}%' ").select('id,name,subname,contact_number').order('name asc')
  end	

  def self.all_conts
     select('id,name,subname,contact_number').order('name asc')
  end

  def total_purchase
    t_amount = 0.0
    self.transactions.each{|t| 

      t_amount -= t.amount.to_f  if t.buyback == 1
      t_amount += t.amount.to_f  if t.buyback != 1

    }
    return t_amount
  end  

  def total_payment
    t_amount = 0.0
    self.transactions.each{|p| 
      t_amount += p.payment_amount.to_f if p.recieved == 1
      t_amount -= p.payment_amount.to_f if p.recieved != 1
    }
    return t_amount
  end  


  def self.paginated_search(p_hash)
    col     = ( p_hash[:column].blank? ?  'id' : p_hash[:column])
    value   = ( p_hash[:value].blank? ?  '' : p_hash[:value])  
    limit   = ( p_hash[:limit].to_i = 0 ? '50' :  p_hash[:limit].to_i)
    order   = ( p_hash[:order].blank? ?  'id' : params[:order])
    offstet =   p_hash[:offset].to_i 

    order_str = params[:order]
    order_str  = 'id'  if order.blank?
    order_str =  "#{order[1..(order.lenght-1)]},desc" if order[0,1] == "-"
    offset = (total_count/page_no) - 1
    total_count = self.where("#{columns} like '%?%'",values).count if total_count.nil?
    contacts  = self.where("#{columns} like '%?%'",values).order(ord_str).limit(offset,limit)
    return contacts,total_count
  end  

  

  def assign_balance
    self.balance = self.starting_balance
  end  
 
  def rectify_contact_balance
     if starting_balance_changed?
        diff = starting_balance.to_f - starting_balance_was.to_f
        self.balance += diff
        sql = "UPDATE transactions set contact_balance = (contact_balance + (#{diff}) ) "
        sql << "where contact_id = #{self.id} "
        p sql
        ActiveRecord::Base.connection.execute(sql)      
     end
  end
    
 

  def rep_trans sdate=nil, edate=nil
     Transaction.where("contact_id = ?  ",self.id).order("on_date DESC , created_at desc")
  end  

  def rep_items sdate=nil, edate=nil
     TxnItem.where("contact_id =? ", self.id).order("id  DESC")
  end  
 
  def rep_payments sdate=nil, edate=nil 
     Payment.where("contact_id =? ", self.id).order("on_date DESC, created_at desc")
  end  

  def aggr_items
     sql =  "SELECT itm.id,itm.name,sum(txn.number) as sum_number, sum(txn.amount) as sum_amount from items itm, txn_items txn "
     sql <<  " where txn.item_id = itm.id and txn.contact_id = #{self.id} group by itm.id"
     Item.find_by_sql(sql)
  end

  def filter_aggr_items
      sql =  "SELECT itm.id,itm.name,sum(txn.number) as number, sum(txn.amount) from items itm, txn_items txn, transactions tx "
      sql <<  " where tx.id= txn.transaction_id and txn.item_id = itm.id and txn.contact_id = #{self.id} group by itm.id"
     

  end  

  def self.picklist
     c_arr = []
     self.order("name").each{|a| 
      c_arr << [a.name_subname, a.id]
     }
     return c_arr
  end  

  def self.total_starting_balance
       t_balance = 0
       self.all.each{|c|  

        t_balance = t_balance + c.starting_balance  if !c.starting_balance.blank?

       } 
       return t_balance
  end  
end

cement/app/models/site.rb
class Site < ActiveRecord::Base
  # attr_accessible :title, :body
  audited
  has_many :contacts
  has_many :transactions
  validates_presence_of :name



  def rep_txnitems contact_id = nil

  	sql = "select ti.*,t.on_date,t.site_id from txn_items ti,transactions t where ti.transaction_id = t.id "
  	sql << " and t.contact_id = #{contact_id} " if  !contact_id.nil?
    sql << " and t.site_id = #{self.id} order by t.on_date desc " 
    
    TxnItem.find_by_sql(sql)
    
  end	

  def self.picklist
     arr = []
     self.order("name").each{|a|

      
      arr << [a.name, a.id]
     }
     return arr
  end  

  
end

cement/app/views/layouts/analytics.erb
<html>
<head>
  <title>Cement-Analytics</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag  "Chart.min.js"%>

  <%= csrf_meta_tag %>

		
</head>
<body>
<%=render :template => "layouts/nav.erb" %>
<div class="container-fluid" style="background-color:#f1f1f1;">
  <div class="row-fluid" style="padding:5px">
   
    <div class="span12"style="text-align:left" id="contacts">
          
            <div id='mnclick' class=" pull-right" style="">
              <span id='menu_arrow' style="color:blue">&#9783<br></span>
            </div>    
            <div id='slider' class='left-pos' style="color:#4c4c4c;">
                     <h5><%=space(5)%>Report Links</h5>
                      <hr style=''>
                      <div class='menu_links'>Balance Report</div>
                      <div class='menu_links'><%=link_to 'Sales Report', sales_analytics_url %></div>
                      <div class='menu_links'>Stock Report</div>


            </div>
               

       <%=yield%>
    </div>


  </div>
      <br><br><span style="color:#f1f1f1;">...</span>
</div>

</body>
</html>
<script type="text/javascript">
$('#mnclick').click(function(event) {
   if( $('#slider').hasClass('left-pos')){

      $('#slider').removeClass('left-pos');
      $('#slider').addClass('right-pos');
      $('#menu_arrow').html("<span style='font-size:35px;color:grey;'>&raquo;</span>");

   }else{
      $('#slider').removeClass('right-pos');
      $('#slider').addClass('left-pos');
      $('#menu_arrow').html('&#9776');

   }

});


  </script>

cement/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
   <%=render :template => "layouts/header.erb" %>
    
</head>
<body link="blue">
<%=render :template => "layouts/nav.erb" %>

<div class="container-fluid">

  <div class="row-fluid" style="padding:5px">

    <div class="span12"style="text-align:left" id="contacts">
          
            <%=yield%>
    </div>


  </div>

</div>
</body>
</html>

cement/app/views/layouts/contacts.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contacts-Cement</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
   <%= csrf_meta_tag %>
   <link href="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap-editable/css/bootstrap-editable.css" rel="stylesheet"/>
<script src="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap-editable/js/bootstrap-editable.min.js"></script>
</head>
<body>
<%=render :template => "layouts/nav.erb" %>

<div class="container-fluid">

  <div class="row-fluid" style="padding:1px">

    <div class="span12"style="text-align:left" id="contacts">
      <%=yield%>
    </div>
  </div>

</div>
</body>
</html>

cement/app/views/layouts/first_page.erb
<div id='start-div' class='row-fluid'>
  <div class="span8 offset2">
  	<%=form_for :user, login_user_path do |f| %>
  	   Test

  	<%end%>

  </div>


</div>

cement/app/views/layouts/header.erb
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
 

cement/app/views/layouts/items.erb
<html>
<head>
     <title>Cement</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
</head>
<body>
<%=render :template => "layouts/nav.erb" %>

<div class="container-fluid">

  <div class="row-fluid" style="padding:5px">

    <div class="span12"style="text-align:left" id="items">
         <% if params[:action] != "all_search"%>
          <%=render :template => "items/_items_header.erb" %>
         <%end%> 
          <%=yield%>
    </div>


  </div>

</div>
</body>
</html>

cement/app/views/layouts/nav.erb
<style>


  .navbar-inverse .nav .active > a, .navbar-inverse .nav .active > a:hover, .navbar-inverse .nav .active > a:focus {
    background-color: #488AC7;

  }

  .navbar-inverse .nav li.dropdown.open > .dropdown-toggle, .navbar-inverse .nav li.dropdown.active > .dropdown-toggle, .navbar-inverse .nav li.dropdown.open.active > .dropdown-toggle {
    background-color: #488AC7;
    color:#FDEEF4;
  }

</style>
<div class="navbar navbar-inverse navbar-fixed-top" style="background-color:#151B54;">
 <div   #4863A0 >

    <ul class="nav" >
    <li >&nbsp;&nbsp;&nbsp;  <i class="fa fa-home brand" style="color:#FFF;padding-right:1px;"></i></li>
     <li> <%=link_to " Cement",  transactions_url, :class=>"brand",:style =>"font-size:14px;color:#FFF;padding-left:10px;"%>

      
     </li>

 
      <li  <% if params[:controller]  == "contacts"%> class='active'<%end%>  style="color:#FDEEF4;"><%=link_to "Contacts", contacts_url %></li>
      <li class="dropdown">
        <a href="#"  class="dropdown-toggle" id="menu_click"><span style="color:#FDEEF4;font-size:22px;" >&#9776;</span> </a>
          <ul class="dropdown-menu" style="width:500px;">

            <div class="row-fluid" style="padding:5px">
   
                <div class="span4"style="text-align:left" id="contacts">
                   <li <% if params[:controller]  == "transactions"%> class='active'<%end%>><%=link_to "Transactions", transactions_url %></li>
            <li <% if params[:controller]  == "payments"%> class='active'<%end%>><%=link_to "Payments", payments_url %></li>
             <li <% if params[:controller]  == "items"%> class='active'<%end%>><%=link_to "Items", items_url%></li>
            <li <% if params[:controller]  == "sites"%> class='active'<%end%>><%=link_to "Sites", sites_url%></li>
           <hr style="margin:5px;">
            <li <% if params[:controller]  == "users"%> class='active'<%end%>><%=link_to "Users", users_url %></li>
             
                </div>
                <div class="span8"style="text-align:left" id="contacts">
                    <li <% if params[:controller]  == "transactions"%> class='active'<%end%>><%=link_to "Transactions", transactions_url %></li>
            <li <% if params[:controller]  == "payments"%> class='active'<%end%>><%=link_to "Payments", payments_url %></li>
             <li <% if params[:controller]  == "items"%> class='active'<%end%>><%=link_to "Items", items_url%></li>
            <li <% if params[:controller]  == "sites"%> class='active'<%end%>><%=link_to "Sites", sites_url%></li>
           <hr style="margin:5px;">
            <li <% if params[:controller]  == "users"%> class='active'<%end%>><%=link_to "Users", users_url %></li>
             
                </div>
            </div>    

            
             
          </ul>
       </li>

               <a class="btn btn-small btn-warning" style="color:#FFF" href="<%=new_stock_entry_url%>"> 
                    <span style='font-weight :bold;font-size:16px;'>+</span><span> Stock</span>
               </a>
                  <a class="btn btn-small btn-success" style="color:#FFF" href="<%=new_payment_url%>">
                    <span style='font-weight :bold;font-size:16px;'>+</span><span> Payment</span>
               </a>

               <a class="btn btn-small btn-primary " style="color:#FFF" href="<%=quick_add_form_transactions_url%>">
                  <span style='font-weight :bold;font-size:16px;'> + </span>  <span> Transaction</span>
                </a>

             
    </ul>
    <ul class="nav navbar-nav pull-right" >
        <li>
            <form class="navbar-search" action="<%=all_search_items_url%>">
                <input name='search' type="text" class="search-query span2" style="background-color:#FAFAFA;color:#585858;height:25px;" placeholder="Search">    
            </form>
        </li>

       <li class="dropdown">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle" style="color:#FFF"> <%=@auser.full_name%>  <b class="caret"></b></a>
          <ul class="dropdown-menu">
               <li><%=link_to "Details", self_details_user_url(:id => @auser.id) %></li>
             <li><%=link_to "Log Out", logout_user_url(:id => @auser.id) %> </li> 
          </ul>
      </li>
          
    </ul>

  </div>

</div>
<br><br>
<div id='mn_dropdown' class='menu-top-hide' style="color:#FFF;font-family: 'Lato',Calibri,Arial,sans-serif;font-size:24px;">
    <div class="row-fluid" style="padding:0px;margin:0px;height:100%;">
   
      <div class="span2 mn-hd-scn" >
         <i id='cog-menu' class="fa fa-cog"></i><%=space(2)%>Menu
      </div>

      <div class="span2 mn-section" >
          <span class='mn-hd'><i class="fa fa-truck"></i><%=space(2)%>Transactions</span><br>
          <%=link_to "Transaction List", transactions_url, {:style=>"line-height:40px;"} %> <br>
          <%=link_to "Add Transaction", quick_add_form_transactions_url %>    
          <br><br><br>
          <div class='mn-hd'> <i class="fa fa-briefcase"></i><%=space(2)%> Payment</div>
          <div ><%=link_to "Payment List", payments_url %> </div>
          <%=link_to "Add Payment", new_payment_url %>   
      </div>


      <div class="span2 mn-section" >
          <span class='mn-hd'><i class="fa fa-cart-arrow-down"></i><%=space(2)%>Items</span><br>
          <%=link_to "Items List", items_url%><br>
          <%=link_to "Item Sales-Stocks", aggrigated_summary_items_url %> <br>
          <%=link_to "Add Item", new_item_url%>
          <br><br>
          <div class='mn-hd'> <i class="fa  fa-cubes"></i><%=space(2)%> Stock Entry</div>
          <div ><%=link_to "Stock Entry List", stock_entries_url %> </div>
          <%=link_to "Add Stock Entry", new_stock_entry_url %>   
      </div>

      <div class="span2 mn-section" >
          <span class='mn-hd'><i class="fa fa-users"></i><%=space(2)%>Contacts</span><br>
          <%=link_to "Contact List", contacts_url%><br>
          <%=link_to "Quick-All Edit", quick_edit_contacts_url%> <br>
          <%=link_to "Add New Contact", new_contact_url%>
          <br><br>
          <div class='mn-hd'> <i class="fa  fa-bank"></i><%=space(2)%> Sites</div>
          <div ><%=link_to "Sites List", sites_url %> </div>
          <%=link_to "Add New Site", new_site_url %>   
      </div>

      <div class="span2 mn-section" style="border-left: 1px solid #5BB7EE">
          <span class='mn-hd'><i class="fa fa-cogs fa-spin"></i><%=space(2)%>Ananlytics</span><br><br>
          <i class="fa fa-dashboard"></i> <%=link_to "Balance Status", status_url %><br>
          <i class="fa fa-line-chart"></i> <%=link_to "Sales Report", sales_analytics_url%> <br>
         <br>
         <i class="fa fa-child"></i><%=link_to "Users", users_url %>
         
      </div>

    </div>

    
             
</div>



<script type="text/javascript">
$('#menu_click').click(function(event) {
   if( $('#mn_dropdown').hasClass('menu-top-hide')){

      $('#mn_dropdown').removeClass('menu-top-hide');
      $('#mn_dropdown').addClass('menu-top-show');
     

   }else{
      $('#mn_dropdown').removeClass('menu-top-show');
      $('#mn_dropdown').addClass('menu-top-hide');
      

   }

});

$('#mn_dropdown a').click(function(event) {

   $("#cog-menu").addClass("fa-spin");
})


  </script>
               

cement/app/views/layouts/payments.erb
<html>
<head>
   <%=render :template => "layouts/header.erb" %>
   <script type="text/javascript">
     
     var search_contacts = [];
     var contact_names = []
    $(document).on('keyup','input.each_amount', {} ,function(e){ 
       
      calculate_payment_amount();
     
        
    });

    $(document).on('keyup','input.keyup_amount', {} ,function(e){ 
       
      calculate_payment_amount();
     
        
    });


    function calculate_payment_amount(){

    	var total = 0.0;
      

      $(".each_amount").each(function(){
           
          if($(this)[0].value  != ''){
            var a = parseFloat($(this)[0].value);
            total = total+a;
          }
       });

       if($("#discount_amount")[0].value != '') {
        total = total + parseFloat($("#discount_amount")[0].value);
         $("#total_amnt").html(indianFormat(parseFloat(total).toFixed(2)) );
      }


    }



    function removeItem(row_no){
     $("#pay_"+row_no).remove();
     calculate_payment_amount();

   }  
   </script> 	
</head>
<body>
<%=render :template => "layouts/nav.erb" %>

<div class="container-fluid">

  <div class="row-fluid" style="padding:5px">

    <div class="span12"style="text-align:left" id="contacts">
            <%=yield%>
    </div>


  </div>

</div>
</body>
</html>

cement/app/views/layouts/reports.erb
<html>
<head>
     <title>Cement</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
</head>
<body>
<%=render :template => "layouts/nav.erb" %>

<div id="sidebar" class="row-fluid" style="padding:0px;margin:0px">
<br>
<%= form_for "report",  :url => generate_reports_url, :remote => true, :html =>{:id=>'report_form'} do |f| %>
 <div class="span12">
     <h6>Select Item(s)</h6>
     <%=hidden_field_tag 'report[r_value]', @r_value%>
    <%=f.select  :item_ids, options_for_select(["Select .."]+Item.picklist), {},{ :multiple => true} %>
 </div>
 <div class="span12">
    <h6>Select Contacts</h6>
    <%=f.select  :contact_ids, options_for_select(Contact.picklist), {},{:multiple => true} %>
 </div>
 <hr>
 <div class="span12">
   <h6>Select Site</h6>
    <%=f.select  :site_ids, options_for_select(["Select .."]+Site.picklist),  {}, {:multiple => true} %>
 <hr class="style-one">
 </div>
 
 <div class="span12">
   <h6>Select Dates</h6>
    <span class='sub_head'> Custom Fixed Date</span>
     <br>
    <%=f.text_field :from_date,  {class: 'report-date', style:'height:30px;width:120px;', :placeholder => "From Date"}%>
      <br>
    <%=f.text_field :to_date,  {class: 'report-date', style:'height:30px;width:120px;', :placeholder => "To Date"}%>
      <br>
      <span class='sub_head' style="color:white"> OR</span>
      <br>
      <span class='sub_head'> Dynamic Dates</span>
      <br>
      Last <%=f.text_field  :number_of, {:style => 'width:60px;height:30px;'} %>
      <%=f.select  :dynamic_date_value,  options_for_select([ "Days","Weeks","Months","Year"]) %>
     
        <hr class="style-one">

        
 </div>

 <div id='group_div' class="span12">
   <h6>Group Aggrigate</h6>
    <%=f.select  :group_order, options_for_select(["Contact", "Item","Timeline","Site


      "]), {},{:multiple => true} %>

        <hr class="style-one">
 </div>
 <div id='timeline'  class="span6" style="display:none">
   <h6>Timeline</h6>
    <%=f.select  :time_line_value, options_for_select(["Daily", "Weekly","ByWeekly","Monthly","Quaterly", "Yearly"])%>
 </div>
   <h6> Report Name</h6>
    <%=f.text_field :name %>
    
 <div id='show_div' class="span12">
 <%=submit_tag "Show" , {class:'btn btn-warning btn-xs', style:'vertical-align: top;'}%>
 <%=submit_tag "Save" , {class:'btn btn-error btn-xs', style:'vertical-align: top;'}%>
 <br><br>
 </div>
</div>
<%end%>

<div id="main" class="row-fluid">
   <div class="span12">
   <br><br>
       <%=yield%>
   </div>
  </div>
</body>
</html>

<script type="text/javascript">

 $('#report_item_ids').select2({
    width:'95%',

 });
  $('#report_contact_ids').select2({
    width:'95%',

 });
   $('#report_site_ids').select2({
    width:'95%',

 });

$('#report_group_order').select2({
    width:'95%',
    maximumSelectionSize: 3,
 });

$('.report-date').datepicker({ dateFormat: 'dd-mm-yy' });



 $(document).ready(function(){


            $('#report_group_order').change(function(){
               if($('#report_group_order').val().indexOf("Timeline") >= 0){
                $('#timeline').show();

               }else{ $('#timeline').hide(); }
            });

           $('#report_time_line_value').width('80%');
           $('#report_dynamic_date_value').width('40%');
        });    

 </script>

cement/app/views/layouts/sites.erb
<html>
<head>
     <title>Cement</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
</head>
<body style='font-size:13px;'>
<%=render :template => "layouts/nav.erb" %>

<div class="container-fluid">

  <div class="row-fluid" style="padding:5px">

    <div class="span12"style="text-align:left" id="items">
          <%=render :template => "sites/_sites_header.erb" %>
          <%=yield%>
    </div>


  </div>

</div>
</body>
</html>

cement/app/views/layouts/transactions.erb
<html>
<head>
  <title>Transactions-Cement</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
   <%= csrf_meta_tag %>
  <script type="text/javascript">
     
     var search_contacts = [];
     var contact_names = []
    $(document).on('keyup','input.item_numbers', {} ,function(e){
       var num =  this.id.split("_")[2];
      var price_e = $("#item_price_"+num)[0];
      var number_e = $("#item_number_"+num)[0];
      var regexDecm =  /^[1-9]\d*(\.\d+)?$/;
      var regexNum =   /[0-9 -()+]+$/ ;
     
      if(price_e.value.match(regexDecm) && number_e.value.match(regexNum)){
        $("#item_val_"+num).html(indianFormat((parseFloat(price_e.value) * parseFloat(number_e.value)).toFixed(2)));
      }else{ $("#item_val_"+num).html('0') }
      
      calc_total_value();

    });




   function calc_total_value(){

       var  i =1;
       var total = 0.0;

       $(".item_total").each(function(){
          if($(this).html() != ''){
            var st = $(this).html().split(',').join('');
            var a = parseFloat(st);
            total = total+a;
          }
       });



/*if($("#transaction_other_charges_amount")[0].value != '') {
        total = total+ parseFloat($("#transaction_other_charges_amount")[0].value);
      }
*/

      if( $("#transaction_vehicle_charges")[0] && $("#transaction_vehicle_charges")[0].value != '') {
        total = total+ parseFloat($("#transaction_vehicle_charges")[0].value);
      }

      if($("#transaction_hamaali")[0] && $("#transaction_hamaali")[0].value != '') {
        total = total+ parseFloat($("#transaction_hamaali")[0].value);
      }
      
      if( $("#transaction_discount")[0] && $("#transaction_discount")[0].value != '') {
        total = total - parseFloat($("#transaction_discount")[0].value);
      }

      ptotal = parseFloat(total).toFixed(2);
      $("#items_total_value").html(indianFormat(ptotal));    

   }

   function removeItem(row_no){
     $("#trow_"+row_no).remove();
     calc_total_value();

   }  

   
   function search_contacts_call(id){
       a =  $("#"+id)[0].value;
       contact_names = [];
       $.ajax({
         type:"Get",
         dataType: 'json',
         url: "<%=search_names_contacts_path()%>",
         data:"str="+a ,
         success: function(data){
           $.each(data, function(i,val){
              contact_names.push(val.name+"  "+val.subname);
           });
           search_contacts = data;
           
         }
       });
       
       return contact_names;

   }

   function show_other_fields(){

     $("#other_link").hide();
     $("#vehicle").show();
     $("#hamaali").show();
     $("#discount").show();
   }

  </script>
</head>
<body>
<%=render :template => "layouts/nav.erb" %>
<div class="container-fluid">
  <div class="row-fluid" style="padding:1px">
    <div class="span12"style="text-align:left" id="items">
    <br>
          <%=yield%>
    </div>


  </div>

</div>

</body>
</html>

cement/app/views/layouts/users.erb
<html>
<head>

   <%=render :template => "layouts/header.erb" %>

</head>
<body>
<%if !@auser.blank? %>
<%=render :template => "layouts/nav.erb" %>
<%end%> 

  <div class="container-fluid">
  <div class="row-fluid" style="padding:1px">
    <div class="span12"style="text-align:left" id="users">
          <%=yield%>
    </div>


  </div>

</div>


</body>
</html>