cement/config/routes.rb
Cement::Application.routes.draw do

  root :to => 'users#welcome'

  resources :items do
      post 'remove', :on => :member
      get  'rep_txnitems', :on => :member
      get  'all_search', :on => :collection
      get  'aggrigated_summary', :on => :collection

  end

  resources :contacts do
    post 'remove', :on => :member
    post  'reports', :on => :member
    post  'ajax_create', :on => :collection

    get 'search_names', :on => :collection
    get  'add_txn', :on => :collection
    get  'window_list', :on => :collection
    get  'report_page', :on => :member
    get 'excel_export', :on => :member

    get 'quick_edit' , :on => :collection
    get 'all_edit' , :on => :collection

    post 'quick_update' , :on => :collection
    post 'all_edit' , :on => :collection
    post 'save_filter', :on => :collection
    post 'filter', :on => :collection
    get  'show_filter', :on => :collection 
    
  end

  resources :transactions do
    post 'remove', :on => :member
    get  'add_item_row', :on => :collection
    post 'pagination', :on => :collection
    get  'quick_add_form', :on => :collection
    post 'quick_add', :on => :collection
  end

  resources :stock_entries do
    post 'remove', :on => :member
    get  'add_item_row', :on => :collection
    post 'pagination', :on => :collection
    get  'quick_add_form', :on => :collection
    post 'quick_add', :on => :collection
    get  'contact_stock', :on => :member
  end

  resources :sites do
    get  'window_list', :on => :collection
    get 'search_names', :on => :collection
    post 'remove', :on => :member
    get 'rep_txnitems', :on => :member
    get 'contact_txnitems', :on => :member
  end

  resources :transaction_types do
      post 'remove', :on => :member

    resources :custom_fields do
      get 'remove', :on => :member
    end  

  end  

  resources :users do
    post 'enter_in', :on => :collection
    get 'ask_signin', :on => :collection
    get 'change_password', :on => :member
    get 'activate', :on => :member
    get 'inactivate', :on => :member
    post 'remove', :on => :member
    put 'save_new_password', :on => :member
    get 'reset_password', :on => :member
    get 'logout', :on => :member
    get  'no_access', :on => :collection
    get  'self_details', :on => :member
  end  

  resources :payments do
      post 'remove', :on => :member
      get  'add_payment_row', :on => :collection
  end   

   resources :reports do
      post 'generate', :on => :collection
      get 'saved_message', :on => :member
      
   end 

   resources :analytics do
      get  'sort_baldtls', :on => :collection
      get  'sales', :on => :collection
      get  'sort_itemsales', :on => :collection
      post 'filter_block1', :on => :collection
      post 'filter_block2', :on => :collection
      post 'filter_block3', :on => :collection
      put  'filter_block1', :on => :collection
   end 

   get "status", to:"analytics#aggr_payments"

end
    
    

cement/app/models/payment.rb
class  Payment < Transaction
   
  default_scope { where(trans_type: 'payment') }
  validate :all_validation
  audited :allow_mass_assignment => true
  belongs_to :contact
  has_many :payment_rows, :foreign_key => :transaction_id
   
  before_create  :calculate_contact_balance, :add_trans_type
  before_update  :rectify_amount
  after_create  :update_balance_changes
  after_update  :update_balance_changes
  after_destroy :destroy_balance_changes
  include BaseUtils
 

  def all_validation
     errors.add(:date, "Date can not be blank") if on_date.blank?
     errors.add(:contact, "Contact can not be blank") if contact.blank?
     errors.add(:payment_amount, "Enter valid payment amount") if payment_amount.blank? || payment_amount.to_i == 0 
  end

  def assign_amount
    a = 0
    self.payment_rows.each{|p|
      a += p.amount
    }
    self.payment_amount = a 
  end  
  
  def is_number?
    self.to_f == self
  end

  def tofrom_contact
  	str = ""
  	str = ( (self.recieved == 1)? " from "+contact.name_subname : " to "+contact.name_subname) if !contact.blank?
    return str
  end	

   
  def name_subname
  	return (contact.blank? ? "":contact.name_subname)
  end	


  def add_trans_type
    self.trans_type = 'payment'
  end  

  def payment_types
    self.payment_rows.collect{|p| p.pay_type}
  end
    
  class << self

    def by_contact ids, sdate=nil, edate=nil
    end  

    def by_date sdate=nil, edate=nil
    end     

  end  


end	

cement/app/controllers/payments_controller.rb
class PaymentsController < ApplicationController


  def index
    sort_column = params[:sort_colum] || 'on_date'
    sort_order = params[:sort_order]  || "DESC"
    page_size = params[:page_size] || 20
    offset = params[:offset] || 0
    @payments = Payment.order("#{sort_column} #{sort_order}, created_at DESC")
  end
  
  def show
  	@payment = Payment.find(params[:id].to_i)
  end
  
  def new
  	@payment = Payment.new
    @site_name = ''
    @cont = Contact.all_conts
    @sites = Site.all
  end 	

  def create

   begin
      @p = Payment.new(params[:payment])
      params[:payment_rows].each{|key,val|

         pr = PaymentRow.new(val)
         @p.payment_rows << pr
      }

      @p.assign_amount
      @p.save!
      flash[:success] = "Payment Added Successfully"
      @payments = Payment.all
      #render js: "window.location.pathname='#{transactions_path}'"
      url = report_page_contact_path(:id => @p.contact_id)
      render js: "window.location.pathname='#{url}'"

   rescue Exception => e
     @trans = @p
     @serr = @e.to_s
     p e.to_s
     respond_to do |format|
       format.js {render layout: false}
     end       
   end 

  end	

  def edit
  	@payment = Payment.find(params[:id].to_i)
    @site_name = (@payment.site.blank? ?  "":@payment.site.name)
    @cont = Contact.all_conts
    @sites = Site.all
  end

  def update

  	@payment = Payment.find(params[:id].to_i)
    payrow_ids = []
     params[:payment_rows].each{|key,val|
      id = key.to_i
      payrow_ids << id

      if id < 1000
        pr = PaymentRow.new(val)
        pr.created_by = @auser.id
        pr.save!
        @payment.payment_rows << pr
      else
        val[:updated_by] = @auser.id
        old_pr = PaymentRow.find(key)
        old_pr.update_attributes(val)
      end 

      } unless  params[:payment_rows].blank?

      @payment.payment_rows.each{|p|

       p.destroy if !payrow_ids.include?(p.id)
      }

    @payment.assign_amount
    @payment.save!
    @payment.update_attributes(params[:payment])
    flash[:notice] = "Payment #{@payment.id} has been updated "
    @trs = Payment.all
    render js: "window.location.pathname='#{payments_path}'"
    
  end

  def remove
  	@payment = Payment.find(params[:id].to_i)
  	@payment.destroy
    redirect_to :action =>'index'
  end


  def add_payment_row
    @row_no = params[:row_no].to_i + 1
    @payment_row = PaymentRow.new(:transaction_id => params[:transaction_id])
    respond_to do |format|
     format.js {render layout: false}
    end
  end  
	
end	

cement/app/views/payments/_date_and_contact.erb
<div id='payment_form' class="row-fluid" >
    <div class="span3">
    <br>  
        <%=f.select  :recieved, options_for_select([["Recieved From:", 1],["Paid To:",0]], ["Recieved From:", 1]),{},{style:'width:150px;'}%>

    </div>
    <div class="span3">
        Contact: <%= link_to '+New', add_txn_contacts_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#contact-modal-window', style: 'font-size:12px;font-weight:bold;'}  %> &nbsp;|
        <%=link_to ((image_tag "find.png", :size=>"16x16")+" List"), window_list_contacts_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#contact-modal-window', style: 'font-size:12px;font-weight:bold;'}  %> 
          <br>
        <%=text_field  :txn, :contact, class:'autocomplete', style:"height:30px;", value: @payment.name_subname%>
        <%=f.hidden_field :contact_id %>
        <br>
        <span id='contact_number' style='color:grey;font-size:14px;'></span>
         <br>
    </div>
    <div class="span3" >
        Date : <br><%= f.text_field :on_date, class:'input', style:'height:30px;width:150px'%>
     </div>
    
 </div>

cement/app/views/payments/_form.erb
<div id='contact-modal-window' class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  Loading ...
</div>
<%= form_for @payment, :remote => true do |f| %>
  

    <%if @payment.new_record?%>

       <%=render :partial => 'date_and_contact', :locals => {:f => f}%>
    <%else%>
           
       <%=render :partial => 'saved_date_contact', :locals => {:f => f}%>

    <%end%>

  <%if !@payment.payment_rows.blank? %>
    <% @payment.payment_rows.each{|prow| %>
     <%=render :partial => 'payment_row', :locals => {:row_no => prow.id, :payment_row => prow}%>
    <%}%>
  <%else%>

      <%=render :partial => 'payment_row', :locals => {:row_no => "1", :payment_row => PaymentRow.new(),:is_first => true}%>
  <%end%>

 
 <div  class="row-fluid" id='add_payment_link'>
    <div class="span3">
     <b><span id='ptype_link'> <%=link_to '+ Payment Type', add_payment_row_payments_path(:row_no => 1 ), :remote => true%></span></b>
    </div>
    <div class="span3">
        Discount Amount<br>
       <%=f.text_field  :discount, id: "discount_amount", class:"keyup_amount", style:"height:30px;" %>
    </div>
    <div class="span3" s>
    <br>
      Total Amount: &nbsp;&nbsp;&nbsp; <span id ='total_amnt'> 
      <%=(@payment.payment_amount + @payment.discount)%>
      </span>
    </div>
</div>


 <div  class="row-fluid" id='note_div'>
    
    <div class="span4">
    <br>
      Note:<br>
      <%=f.text_area  :descri,  :size => '3x2'%>

    </div>
    
 </div>



<div class="row-fluid">
  <div class="span12">
     <hr>
    <%=space(10).html_safe%> <%=f.submit :id => "button_id", :class => "button", :data => {disable_with: "Submitting..."}  %><%=space(5).html_safe%> <%=link_to "Cancel", payments_url, :style=>"font-weight:bold"%>
  </div>
</div>
<% end %>



<script type="text/javascript">
  

  $('#payment_on_date').datepicker({ dateFormat: 'dd-mm-yy' });
  $("#payment_on_date").datepicker('setDate', new Date());
  var contact_names = [];
  var search_contacts = {};


  $('#txn_contact').autocomplete({
    minLength: 2,
    source: function (request,response){
               a =  $("#txn_contact")[0].value;
               $.ajax({
               type:"Get",
               dataType: 'json',
               url: "<%=search_names_contacts_path()%>",
               data:"str="+a ,
               success: function(data){
                contact_names = [];
                search_contacts = {};
                 $.each(data, function(i,val){
                    
                    n_name = (val.subname == null ? val.name : val.name+" "+val.subname)
                    contact_names.push(n_name);
                    search_contacts[n_name] = val;
                 });
                   
               }
             });
              response(contact_names);
           },
    select: function( event, ui ) { 
              alert(search_contacts[ui.item.value].id.toString());
                $('#payment_contact_id').val(search_contacts[ui.item.value].id.toString());
                 $('#contact_number').html("Ph: "+search_contacts[ui.item.value].contact_number)

              }       

  });
</script> 

cement/app/views/payments/_form_2.erb
<div id='contact-modal-window' class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  Loading ...
</div>
<%= form_for @payment, :remote => true do |f| %>

<div id='div_item_table' class="row-fluid txn-form" style="border:0;">
   <div class="span2" >
   </div>
 <div class="span8">
    <table id='item_tb' class='paymnt' style="border:1px solid #e6e6e6; background-color: #f1f1f1;">
      <thead style="font-size:12px;">
      </thead> 
      <tbody style='font-size:13px;'>
         <tr id='first_row_fields'>
           <%if @payment.new_record?%>
               <td>
               <br>  
                 <%=f.select  :recieved, options_for_select([["Recieved From:", 1],["Paid To:",0]], ["Recieved From:", 1]),{},{style:'width:150px;'}%>

              </td>
             <td>
                Contact: <%= link_to '+New', add_txn_contacts_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#contact-modal-window', style: 'font-size:12px;font-weight:bold;'}  %> &nbsp;|
        <%=link_to ((image_tag "find.png", :size=>"16x16")+" List"), window_list_contacts_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#contact-modal-window', style: 'font-size:12px;font-weight:bold;'}  %> 
          <br>
        <%=text_field  :txn, :contact, class:'autocomplete', style:"height:30px;", value: @payment.name_subname%>
        <%=f.hidden_field :contact_id %>
        <br>
        <span id='contact_number' style='color:grey;font-size:14px;'></span>
        </td>
    <td style="padding:20px;padding-bottom:10px;">
        Date : <br><%= f.text_field :on_date, class:'input', style:'height:30px;width:150px'%>
     </td>
    
       
           <%else%>
                <td style="padding:20px;padding-bottom:10px;">
                  <%if @payment.recieved? %>
                      Recieved From:
                 <%else%>
                      Paid To:
                 <%end%>

                </td>
                <td>
                   Contact: <%= @payment.contact.name_subname%>
                   <br>
                   <span id='contact_number' style='color:grey;font-size:14px;'><%=@payment.contact.contact_number%></span>
               </td>
                 <td>
                 Date : <%=@payment.on_date%>
                 </td>

            <%end%>
             
          </tr>
          
           <tr class ='bottom_line'>
             <td colspan='3'>
     <b><span id='ptype_link' style="font-size:11px;"> <%=link_to ((image_tag "add.png", :size=>"11x11")+'Payment Type'), add_payment_row_payments_path(:row_no => 1 ), :remote => true%></span></b>
    </td>
             

           </tr>
    

  <%if !@payment.payment_rows.blank? %>
    <% @payment.payment_rows.each{|prow| %>
     <%=render :partial => 'payment_row_2', :locals => {:row_no => prow.id, :payment_row => prow}%>
    <%}%>
  <%else%>

      <%=render :partial => 'payment_row_2', :locals => {:row_no => "1", :payment_row => PaymentRow.new(),:is_first => true}%>
  <%end%>

 
 <tr id='add_payment_link' class="bottom_line">
    
    <td >
        Discount Amount<br>
       <%=f.text_field  :discount, id: "discount_amount", class:"keyup_amount", style:"height:30px;width:100px;" %>
    </td>
     <td style="padding-left:10px;">Site:  <%=link_to ((image_tag "find.png", :size=>"12x12")+" List"), window_list_sites_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#contact-modal-window', style: 'font-size:12px;'}  %> <br> 
        <%=text_field  :txn, :site, class:'autocomplete', style:"height:30px;", :value => @site_name%> <br>
        <%=f.hidden_field :site_id %></td>
    <td >
      Total Amount: <%=space(3)%>

       <span id ='total_amnt' style='color:blue;font-weight:600;'> 
        <%=Utility.indian_number (@payment.payment_amount + @payment.discount)%>
      </span>
    </td>
</tr>


 <tr   id='note_div' class='bottom_line'>
    
    <td colspan=3>
      Note:<br>
      <%=f.text_area  :descri,  :size => '3x2'%>

    </td>
    
 </tr>
 <tr>
   <td colspan="3">
       <%=f.submit "Add Payment",:id => "button_id", :class => 'btn btn-warning', :data => {disable_with: "Submitting..."}  %><%=space(5).html_safe%> <%=link_to "Cancel", payments_url, :style=>"font-weight:bold"%>
   </td>
 </tr>
 </tbody>
 </table>
 </div>
 </div>



<div class="row-fluid">
  <div class="span12">
     <hr>
    <%=space(10).html_safe%> 
  </div>
</div>
<% end %>



<script type="text/javascript">
  

  $('#payment_on_date').datepicker({ dateFormat: 'dd-mm-yy' });
  $("#payment_on_date").datepicker('setDate', new Date());

  var contact_names = [];
  var search_contacts = {};
  var search_sites = {}
  var site_names = []

   <% @cont.each{|c| %>

                    n_name = "<%=(c.subname == nil ? c.name : c.name+' '+c.subname)%>"
                    contact_names.push(n_name);
                    var cnt = {
                      id :"<%=c.id%>",
                      contact_number : "<%=c.contact_number%>",
                    }
                    search_contacts[n_name] = cnt;
   <%}%>

  <% @sites.each{|c| %>
                    site_names.push("<%=c.name%>");
                    search_sites["<%=c.name%>"] = <%=c.id%>;
   <%}%>


  $('#txn_contact').autocomplete({
    minLength: 1,
    source: function (request,response){
               a =  $("#txn_contact")[0].value;
                c_names = []
               $.each(contact_names, function( index, value ) {

                 if(value.toLowerCase().startsWith(a.toLowerCase())){
                  c_names.push(value)
                 }
              });
              response(c_names); 
           },
    select: function( event, ui ) { 
              
                $('#payment_contact_id').val(search_contacts[ui.item.value].id.toString());
                $('#contact_number').html("Ph: "+search_contacts[ui.item.value].contact_number)

              }       

  });

 $('#txn_site').autocomplete({
    minLength: 1,
    source: function (request,response){
               a =  $("#txn_site")[0].value;
               s_names = []
             $.each(site_names, function( index, value ) {
            
                 if(value.toLowerCase().startsWith(a.toLowerCase())){
                  s_names.push(value)
                 }
              });
              response(s_names);
           },
     select: function( event, ui ) { 
      $('#payment_site_id').val(search_sites[ui.item.value].toString());}       

  });
</script> 

cement/app/views/payments/_header.erb
<div class="row-fluid" id="items_tab">
      <br><br>
       <%=link_to "Payments List",payments_url,  :id=>'list', :class=>'label-success label'%>
       &nbsp;&nbsp;
      <%=link_to "New Payment", new_payment_url, :id=>'add' , :class=>'label-success label'%>
      <hr style="margin:5px;">
</div>

cement/app/views/payments/_list.erb
<% sum = 0 %>
<table class="table zebra-striped table-condensed" style='font-size:12px;width:80%' align="center">
  <thead style="background-color:#ff9999;">
    <th>Payment#</th>
    <th>Date</th>    
    <th>Details</th>
    <th>Contact</th>
    <th>Amount</th>
    <% if params[:commit] != 'Print View' %>
     <th>Account Balance</th>
     <th style="color:#330099">Action</th>
     <%end%>
  </thead>
  <tbody>
   <% i = 0
    @payments.each{|c|
     i+= 1

     sum += c.payment_amount if c.recieved == 1
     sum -= c.payment_amount if c.recieved != 1
      %>
    <%if i%2 == 0%>
       <tr>
    <%else%>
       <tr class="info">
    <%end%>

    <td><%=c.id%></td>
    <td><%=c.on_date%></td>
    <td><%c.payment_rows.each {|p| %>

       <%=p.pay_type%> : <%if !p.note.blank?%> <%=p.note%>  : <%end%> <%=p.amount%> <br>
     <% }%>
     <% if ( c.discount.to_i > 0)  %>Discount : <%=c.discount%><br> <%end%><%=c.payment_note%></td>
    <td><%=c.tofrom_contact%>
        <%if !c.site_id.blank? %>
           <br>Site: <%=c.site.name%>
        <%end%>
    </td>
    <td><%if c.recieved != 1%> -<%end%><%=Utility.indian_number c.payment_amount %></td>
    <% if params[:commit] != 'Print View' %>
    <td><% if !c.contact.nil?%><%=Utility.indian_number (c.contact_balance.to_s.to_f + c.contact.starting_balance.to_s.to_f)%><%end%></td>
    <td>
          <span id ='t1'>
          <%=link_to "Edit", edit_payment_url(c.id), :class=>"label label-info"%><%=space(5).html_safe%>
         </span>
         <span id='t2'>
          <%=link_to "Delete", remove_payment_url(c.id), :method => :post, :onclick => "return confirm('Are you sure?')", :class=>"label label-warning"%>
         </span>
      </td>
      <%end%>
   </tr>
   <%}%>
   <tr><td></td></tr>
   <tr class ='success' ><td></td>
    <td><b>Total </b></td>
    <td><b><%=@payments.size%> Payments </b></td>
    <td></td>
    <td><b><%= Utility.indian_number sum%></b></td>
    <td></td>
    <td></td>
    </tr>
  </tbody>

</table>

cement/app/views/payments/_payment_row.erb
 
<% payment_row ||= PaymentRow.new() 
   payment_row.id ||= row_no.to_i %>

<%= fields_for "payment_rows[]", payment_row do |p| %>
   <div  class="row-fluid" id="pay_<%=row_no%>">
     <div class="span3">
        Payment Type:<br>
        <%=p.select  :pay_type,  options_for_select(["Cash","Cheque/DD", "Bank Transaction"],[payment_row.pay_type,payment_row.pay_type]),{},{style:'width:150px;'} %>

    </div>
    <div class="span3">
      Payment Info:<br>
      <%=p.text_field  :note, style:"height:30px;" %>
    </div>
    <div class="span3">
        Amount:<br>
       <%=p.text_field  :amount, id:"amount_#{row_no}", class:"each_amount", style:"height:30px;" %>
    </div>
    <div class='span2'>
     <%=link_to_function "-", "removeItem('#{row_no}')", style:'font-size:15px;font-weight:bold;'%>
  </div>
  </div>  
  
 <%end%> 

cement/app/views/payments/_payment_row_2.erb
 
<% payment_row ||= PaymentRow.new() 
   payment_row.id ||= row_no.to_i %>

<%= fields_for "payment_rows[]", payment_row do |p| %>
   <tr  id="pay_<%=row_no%>">
       <td>
        <%=p.select  :pay_type,  options_for_select(["Cash","Cheque/DD", "Bank Transaction"],[payment_row.pay_type,payment_row.pay_type]),{},{style:'width:150px;'} %>

    </td>
    <td >
      <%=p.text_field  :note, style:"height:30px;", :placeholder => "Payment Info" %>
    </td>
    <td>
       <%=p.text_field  :amount, id:"amount_#{row_no}", class:"each_amount", style:"height:30px;", :placeholder => "Amount" %>

      <%=link_to_function  (image_tag "cross_circle.png", :size=>"12x12"), "removeItem('#{row_no}')", style:'font-size:15px;font-weight:bold;'%>
    </td>
  </tr>  
  
 <%end%> 

cement/app/views/payments/_saved_date_contact.erb
<div id='payment_form' class="row-fluid" >
    <div class="span3">
      <%if @payment.recieved? %>
         Recieved From:
      <%else%>
         Paid To:
      <%end%>

    </div>
    <div class="span3">
        Contact: <%= @payment.contact.name_subname%>
        <br>
        <span id='contact_number' style='color:grey;font-size:14px;'><%=@payment.contact.contact_number%></span>
         <br>
    </div>
    <div class="span3" >
        Date : <%=@payment.on_date%>
     </div>
    <br>
 </div>

cement/app/views/payments/add_payment_row.js.erb
$('#add_payment_link').before("<%= j(render  :template => 'payments/_payment_row_2.erb', :locals => {:row_no => @row_no, :payment_row => @payment_row} ) %>");
$('#ptype_link').html("<%=j (link_to ((image_tag 'add.png', :size=>'12x12')+'Payment Type'), add_payment_row_payments_path(:id => '0',:row_no => @row_no ), :remote => true)%></td>")

cement/app/views/payments/create.js.erb
<% @trans = @p %>
$('#new_payment').before("<%= j(render  :template => 'transactions/_trans_error.erb', :locals => {:trans => @trans} ) %>");

cement/app/views/payments/edit.erb
<h5>Edit Payment</h5>
<%=render :partial => 'form_2'%>

cement/app/views/payments/index.erb
<div id="index_head" class="row-fluid" style="padding:0px;margin:0px">
 <div class="span8">
   <h5>Payments</h5>
   <%if !flash[:notice].blank? %>
   <div class="alert alert-success">
   <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;
   </button>
    <%=flash[:notice]%></div>
    <%end%>
 </div>
</div>

<div id="index_list" class="row-fluid">

   <div class="span12">
    
     <%=render :partial => "list" %>

 </div>
  </div>

cement/app/views/payments/new.erb
<h5>Add Payment</h5>
<%=render :partial => 'form_2'%>