cement/config/routes.rb
Cement::Application.routes.draw do

  root :to => 'users#welcome'

  resources :items do
      post 'remove', :on => :member
      get  'rep_txnitems', :on => :member
      get  'all_search', :on => :collection
      get  'aggrigated_summary', :on => :collection

  end

  resources :contacts do
    post 'remove', :on => :member
    post  'reports', :on => :member
    post  'ajax_create', :on => :collection

    get 'search_names', :on => :collection
    get  'add_txn', :on => :collection
    get  'window_list', :on => :collection
    get  'report_page', :on => :member
    get 'excel_export', :on => :member

    get 'quick_edit' , :on => :collection
    get 'all_edit' , :on => :collection

    post 'quick_update' , :on => :collection
    post 'all_edit' , :on => :collection
    post 'save_filter', :on => :collection
    post 'filter', :on => :collection
    get  'show_filter', :on => :collection 
    
  end

  resources :transactions do
    post 'remove', :on => :member
    get  'add_item_row', :on => :collection
    post 'pagination', :on => :collection
    get  'quick_add_form', :on => :collection
    post 'quick_add', :on => :collection
  end

  resources :stock_entries do
    post 'remove', :on => :member
    get  'add_item_row', :on => :collection
    post 'pagination', :on => :collection
    get  'quick_add_form', :on => :collection
    post 'quick_add', :on => :collection
    get  'contact_stock', :on => :member
  end

  resources :sites do
    get  'window_list', :on => :collection
    get 'search_names', :on => :collection
    post 'remove', :on => :member
    get 'rep_txnitems', :on => :member
    get 'contact_txnitems', :on => :member
  end

  resources :transaction_types do
      post 'remove', :on => :member

    resources :custom_fields do
      get 'remove', :on => :member
    end  

  end  

  resources :users do
    post 'enter_in', :on => :collection
    get 'ask_signin', :on => :collection
    get 'change_password', :on => :member
    get 'activate', :on => :member
    get 'inactivate', :on => :member
    post 'remove', :on => :member
    put 'save_new_password', :on => :member
    get 'reset_password', :on => :member
    get 'logout', :on => :member
    get  'no_access', :on => :collection
    get  'self_details', :on => :member
  end  

  resources :payments do
      post 'remove', :on => :member
      get  'add_payment_row', :on => :collection
  end   

   resources :reports do
      post 'generate', :on => :collection
      get 'saved_message', :on => :member
      
   end 

   resources :analytics do
      get  'sort_baldtls', :on => :collection
      get  'sales', :on => :collection
      get  'sort_itemsales', :on => :collection
      post 'filter_block1', :on => :collection
      post 'filter_block2', :on => :collection
      post 'filter_block3', :on => :collection
      put  'filter_block1', :on => :collection
   end 

   get "status", to:"analytics#aggr_payments"

end
    
    

cement/app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base

   attr_accessor :password, :password_confirmation
   include BCrypt
  
   include BaseUtils
   
   audited :allow_mass_assignment => true

   before_save :encrypt_password

  

  validates_confirmation_of :password
  validates_presence_of :email, :message => "Email Address can not be blank "
  validates_length_of :username ,:minimum => 4, :message => "Username should have minimum 4 charector"
  #validates_uniqueness_of :email, :message => "Email #{self.email} already registered. Please enter a different one"
 # validates_uniqueness_of :username, :message => "Username #{self.username} already exists. Please enter a  different one."


  def generate_password
  	self.password =  (('0'..'9').to_a+('A'..'Z').to_a+('a'..'z').to_a).shuffle.first(6).join
  	p "Password"
  	p self.password
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def send_creational_email
  end	

  def self.authenticate(username, password)
    user = find_by_username(username)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end



   def self.current_user
   	  Thread.current[:auser]
   end	
  
   def self.current_user= user
   	  Thread.current[:auser] = user
   end

   
  


end

cement/app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_filter :authorize , only: [:ask_signin,:enter_in]
    skip_before_filter :accessable, only: [:no_access,:ask_signin, :enter_in]

 def index
 	 @users = User.all
 end
 
 def show
 end	

 def new
  raise 'You are not authorized to do this' if @auser.role  != 'Admin'
 	@user = User.new
 end
 
 def create
  raise 'You are not authorized to do this' if @auser.role  != 'Admin'
 	params[:user]['change_password'] = '1'
 	@user = User.new(params[:user])
 	if @user.valid?
	 	 @user.generate_password
     UserMailer.welcome_email(@user).deliver
	 	 @user.save!
	 	
	else 
       @user.errors.each{|e|   e}
	     render new
	end	
 	redirect_to :controller=> 'users', :action => 'index'
 end

 def edit
   raise 'You are not authorized to do this' if @auser.role  != 'Admin'
   @user = User.find(params[:id])
 end	

 def update
    raise 'You are not authorized to do this' if @auser.role  != 'Admin'
    @user = User.find(params[:id])
    @user.update_attributes(params[:user])
    flash[:info] = "Updated the user #{@user.full_name}'s details successfully"
    redirect_to :controller=> 'users', :action => 'index'

 end

 def destroy
  raise 'You are not authorized to do this' if @auser.role  != 'Admin'
 end	

def remove
  raise 'You are not authorized to do this' if @auser.role  != 'Admin'
   User.find(params[:id]).destroy
   redirect_to :action => 'index'
 end

 def inactivate
  raise 'You are not authorized to do this' if @auser.role  != 'Admin'
 	a = User.find(params[:id])
    a.active = 0
    a.save!
   redirect_to :action => 'index'
 end
 
 def activate
  raise 'You are not authorized to do this' if @auser.role  != 'Admin'
 	a = User.find(params[:id])
    a.active = 1
    a.save!
   redirect_to :action => 'index'
 end	


 def welcome	
 	redirect_to  :controller => 'transactions', :action => "index" , :user => @user 
 end

 def ask_signin
 end	

 def enter_in

 	@user = User.authenticate(params[:username], params[:password])
 	if @user.nil?
 		flash[:error] = "Invalid username or password"
 		redirect_to :action => "ask_signin"
 	elsif @user.change_password == 1
       session[:user_id] = @user.id
       redirect_to :action => 'change_password', :id => @user.id
  else	
      session[:user_id] = @user.id
 	    redirect_to  :controller => 'transactions', :action => "index" , :user => @user		
  end		
    return
  end	

  def no_access
  end 

  def reset_password
   
   begin
    raise 'You are not authorized to do this' if @auser.role  != 'Admin'
    @user = User.find(params[:id])
    @user.generate_password
    @user.change_password = 1
    UserMailer.password_reset(@user).deliver
    @user.save!
    flash[:info] = 'Password has been reset successfully for '+@user.full_name
    flash[:info] += "  Email has been sent to "+@user.email
   rescue Exception => e
     flash[:info] = "Password reset was UNSUCCESS. "+e.to_s
   end 
   redirect_to :action => 'index'
  end  

  def change_password
     @user =  User.find(params[:id])
  end	
  
  def save_new_password
    flash[:error] = ''
    flash[:info] = ''
    begin
      params[:user][:change_password] = 0
      @user = User.find(params[:id])
      raise 'You are not authorized to change the password for this user' if @user.id != @auser.id
      @user.update_attributes(params[:user])
      flash[:info] = 'Password changed successfully, Use new password with you next login'
      session[:user_id] = nil
      @user = User.find(params[:id])
      render :template =>  'users/welecome.erb'
     rescue Exception => e 
       flash[:error] = 'Password didnot changed, Try again. '+e.to_s
       redirect_to :action => 'change_password', :id => @user.id
     end 
  end	

  def logout
    session[:user_id] = nil
    @auser = nil
    flash[:error] = "Log out Successfull"
    redirect_to :action => "ask_signin"
  end  

  def sel_details
  end  

end

cement/app/helpers/user_helper.rb
module UserHelper
end

cement/app/views/users/_form.erb
<%= form_for @user do |f| %>
<div class="row-fluid">

  <div class="span12">
    <div class="row-fluid">
      <div class="span4" style='text-align:right;'>Login Username: </div>
      <div class="span4"><%= f.text_field :username, style:'height:30px;' %> </div>
    </div>
    <div class="row-fluid">
      <div class="span4" style='text-align:right;'>User Role </div>
      <div class="span4"><%= f.select :role, options_for_select(["General","Data Entry", "Admin"], selected_key = f.object.role) %> </div>
    </div>
    <div class="row-fluid">
      <div class="span4" style='text-align:right;'>User Full Name: </div>
      <div class="span4"><%= f.text_field :full_name , style:'height:30px;'%> </div>
    </div>

    <div class="row-fluid">
      <div class="span4" style='text-align:right;'>Email: </div>
      <div class="span4"><%= f.text_field :email , style:'height:30px;width:300px;'%> </div>
    </div>

    <div class="row-fluid">
      <div class="span4" style='text-align:right;'>Phone #: </div>
      <div class="span4"><%= f.text_field :contact_number, style:'height:30px;'%> </div>
    </div>
    <div class="row-fluid">
      <div class="span4" style='text-align:right;'>Adress </div>
      <div class="span4"><%= f.text_area :address, :rows => '3'%> </div>
    </div>
    <div class="row-fluid">
      <div class="span4" style='text-align:right;'>Start Date: </div>
      <div class="span4"><%= f.text_field :start_date, class:'input', style:'height:30px;'%> </div>
    </div>
    <div class="row-fluid">
      <div class="span4" style='text-align:right;'>Othe Information </div>
      <div class="span4"><%= f.text_area :info,  :rows => '3'%> </div>
    </div>

  </div>


</div>

<div class="row-fluid">
  <div class="span12">
     <hr>
    <%=space(10).html_safe%> <%= f.submit %><%=space(5).html_safe%> <%=link_to "Cancel", users_url, :style=>"font-weight:bold"%>
  </div>
</div>
<% end %>


<script type="text/javascript">
  $('#user_start_date').datepicker({ dateFormat: 'yy-MM-dd' });
  $("#user_start_date").datepicker('setDate', new Date());
</script>

cement/app/views/users/_header.erb
<div class="row-fluid">
  <ul class="nav nav-pills offset1" style="margin:5px;">
   <li style="font-weight:bold;"><%=link_to "List",users_url%></li>
   <li style="font-weight:bold;">
 <%=link_to "Add", new_user_url%></li>
</ul>

</div>
<hr style="margin:5px;">

cement/app/views/users/ask_signin.erb
<div class="row-fluid" style="padding:1px">
    <div class="span8 offset2"style="text-align:left" id="users">
        <div  class="well" style="background-color:#6F5499;color:#ffffff">
        	<span style="font-size:22px;font-weight:bolder;">Vardhan Agencies</span>&nbsp;&nbsp;
        	<span style="color:#CDBFE3;font-size:14px;">C.P Bazar, Sirsi (Uttara Kannada)</span>
        </div>
		<div class="well well-lg">
		 
		 <%= form_tag enter_in_users_path do %>
		 		<h4 class="form-signin-heading">Please sign in</h4>
		 		<span style="color:red;"><%=flash[:error]%></span>
		 		<br>
		<input name="username" type="text" class="form-control" placeholder="User name" required="" autofocus="" style="height:30px;"/>
		 <br>
		<input name="password" type="password" class="form-control" placeholder="Password" required=""  style="height:30px;"/>
		<label class="checkbox">
		<input type="checkbox" value="remember-me"/>
		Remember me
		</label>
		<button class="btn  btn-success" type="submit">Sign in</button>
		<%end%>
		</div>

</div>
</div>

cement/app/views/users/change_password.erb
<%= form_for  @user, :url => save_new_password_user_path do |f| %>
<div class="row-fluid">

  <div class="span12">
    <div class="row-fluid">
    <br><br>
      <div class="span8" ><b>Change the password to access the application</b>
         <%if !flash[:error].blank?%>
             <div class="alert alert-warning" role="alert"><%=flash[:error]%></div>
          <%end%>

      </div>
      
    </div>
    <div class="row-fluid">
      <div class="span4" style='text-align:right;'>New Password </div>
      <div class="span4"><%= f.text_field :password, style:'height:30px;' %> </div>
    </div>
    <div class="row-fluid">
      <div class="span4" style='text-align:right;'>Confirm New Password</div>
      <div class="span4", style:'height:30px;'><%= f.text_field :password_confirmation %> </div>
    </div>
    <div class="row-fluid">
  <div class="span12">
    <%=hidden_field_tag('save_new_password','1')%>
     <hr>
    <%=space(10).html_safe%> <%= f.submit "Change Password" %><%=space(5).html_safe%> <%=link_to "Cancel", transactions_url, :style=>"font-weight:bold"%>
  </div>
</div>
 <%end%>   

cement/app/views/users/edit.erb
<%=render :template => "users/_header.erb" %>
<h5> Edit User <span style="color:#0101DF"><%=@user.full_name%> </span></h5>
<%= render :partial => 'form'%>

cement/app/views/users/index.erb
<%=render :template => "users/_header.erb" %>
<h4>Users</h4>
<%if !flash[:info].blank?%>
 <div class="alert alert-warning"><%=flash[:info]%></div>
<%end%>
<table class="table zebra-striped table-condensed" style='font-size:13px;'>
  <thead style="background-color:#C0C0C0;">
    <th>Username</th>
    <th>Name</th>    
    <th>Email</th>
    <th>Active</th>
    <th></th>
    <%if @auser.role == 'Admin'%>
    <th style="color:#330099">Action</th>
    <%end%>
  </thead>
  <tbody>
   <% i = 0
    @users.each{|c|
     i+= 1 %>
    <%if i%2 == 0%>
       <tr>
    <%else%>
       <tr class="info">
    <%end%>

    <td><%=c.username%></td>
    <td><%=c.full_name%></td>
    <td><%=c.email%></td>
    <td><%= (c.active == 1 ? 'Active': 'Inactive')%></td>
    <td></td>
    <%if @auser.role == 'Admin'%>

    <td>
          <span id ='t1'>
          <%=link_to "Edit", edit_user_url(c.id), :class=>"label label-info"%><%=space(5).html_safe%>
         </span>
         <span id='t2'>
          <%=link_to "Delete", remove_user_url(c.id), :method => :post, :onclick => "return confirm('Are you sure?')", :class=>"label label-warning"%>
         </span>
         <%if c.active == 1 %>

            <%=link_to "Inctivate", inactivate_user_url(c.id), :class=>"label label-danger"%><%=space(5).html_safe%>
          <%else%>
            <%=link_to "Activate", activate_user_url(c.id), :class=>"label label-success"%><%=space(5).html_safe%>  
         <%end%>
         <%if c.id == @auser.id%>
           <%=link_to "Change Password", change_password_user_url(c.id), :class=>"label label-success"%><%=space(5).html_safe%>  
         <%else%>  
          <%=link_to "Reset Password", reset_password_user_url(c.id), :class=>"label label-success"%><%=space(5).html_safe%>  
          <%end%>
      </td>
     <%end%> 
   </tr>
   <%}%>
  </tbody>

</table>

cement/app/views/users/new.erb
<%=render :template => "users/_header.erb" %>
<h5> Add New User </h5>
<%if !@user.errors.blank? %>
<%@user.errors.each{|e| %>
  <div class="alert alert-warning"><%=e.to_s%></div>
  <%}%>
<%end%>
<%= render :partial => 'form'%>

cement/app/views/users/no_access.erb
<br>
<div id='no_access' style ="background:url('/assets/acden.jpeg') no-repeat center center ;width:100%;height:80%">
<br><br>
   <%=image_tag 'images.jpeg', :size=>'40x40'%><span style="font-size:22px;color:#900000;font-weight:bold;">  Sorry !!</span>
    <span style="font-size:18px;color:#666633;font-weight:bold;"> &nbsp;&nbsp;You do not have access for thia action </span>
</div>

cement/app/views/users/self_details.erb
<%= form_for @auser do |f| %>
<div class="row-fluid">
<br><br><br>
  <div class="span12">
    <div class="row-fluid">
      <div class="span4" style='text-align:right;'>Login Username: </div>
      <div class="span4"><%= f.text_field :username, style:'height:30px;' %> </div>
    </div>

    <div class="row-fluid">
      <div class="span4" style='text-align:right;'>User Full Name: </div>
      <div class="span4"><%= f.text_field :full_name , style:'height:30px;'%> </div>
    </div>

    <div class="row-fluid">
      <div class="span4" style='text-align:right;'>Email: </div>
      <div class="span4"><%= f.text_field :email , style:'height:30px;width:300px;'%> </div>
    </div>

    <div class="row-fluid">
      <div class="span4" style='text-align:right;'>Phone #: </div>
      <div class="span4"><%= f.text_field :contact_number, style:'height:30px;'%> </div>
    </div>
    <div class="row-fluid">
      <div class="span4" style='text-align:right;'>Adress </div>
      <div class="span4"><%= f.text_area :address, :rows => '3'%> </div>
    </div>

  </div>

<div class="row-fluid">
  <div class="span12">
     <hr>
    <%=space(10).html_safe%> <%= f.submit %><%=space(5).html_safe%> <%=link_to "Cancel", users_url, :style=>"font-weight:bold"%>
  </div>
</div>
<%end%>

cement/app/views/users/welcome.html.erb
<%if !flash[:info].blank?%>
      <div class="alert alert-warning" role="alert"><%=flash[:info]%></div>
 <%end%>